version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.12.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t openq/openq-oracle:$CIRCLE_TAG .
      - run: docker push openq/openq-oracle:$CIRCLE_TAG
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: OpenQ
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^local*/
                - /^development*/
                - /^staging*/
                - /^production*/
